apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-srv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-srv1
  template:
    metadata:
      labels:
        app: app-srv1
    spec:
      containers:
        - name: app-srv1
          image: sureshmavp1/app-srv1:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000