apiVersion: v1
kind: Service
metadata:
  name: app1-20-feb-demo
spec:
  selector:
    app: app1-20-feb-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP