apiVersion: v1
kind: Service
metadata:
  name: argocd-test1-new
spec:
  selector:
    app: argocd-test1-new
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP