apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-uitest1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-uitest1
  template:
    metadata:
      labels:
        app: argocd-uitest1
    spec:
      containers:
        - name: argocd-uitest1
          image: sureshmavp1/argocd-uitest1:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000