apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-uitest3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-uitest3
  template:
    metadata:
      labels:
        app: argo-uitest3
    spec:
      containers:
        - name: argo-uitest3
          image: sureshmavp1/argo-uitest3:1.0.1
          imagePullPolicy: Always
          # ports:
          #   - containerPort: 3000